Enable `boot.scr` on the fly using `custom.txt`
This is not recommended

Signed-off-by: Patrick Yavitz <pyavitz@gmail.com>

diff --git a/lib/function/staging b/lib/function/staging
--- a/lib/function/staging
+++ b/lib/function/staging
@@ -347,38 +347,31 @@ EOF
 }
 
 customize_image (){
-# edit board.txt variables before the file gets sourced
-if [[ `grep -w 'FAMILY_EXT="odroid"' "board.txt"` ]]; then
-	if [[ "$ENABLE_PETITBOOT" == "true" ]]; then
-		sed -i 's/P_VALUE="p1"/P_VALUE="p2"/g' board.txt
-		sed -i 's/EXTLINUX="true"/EXTLINUX="false"/g' board.txt
-		sed -i 's/PETITBOOT="false"/PETITBOOT="true"/g' board.txt
-	fi
+if [[ ! -f "custom.txt" ]]; then echo "custom.txt is missing! Run make config."; exit 1; fi
+# Edit board.txt variables before the file gets sourced
+if [[ `grep -w 'FAMILY_EXT="odroid"' "board.txt"` ]] && [[ "$ENABLE_PETITBOOT" == "true" ]]; then
+	sed -i 's/P_VALUE="p1"/P_VALUE="p2"/g' board.txt
+	sed -i 's/EXTLINUX="true"/EXTLINUX="false"/g' board.txt
+	sed -i 's/PETITBOOT="false"/PETITBOOT="true"/g' board.txt
 fi
-if [[ -f "custom.txt" ]] && [[ "$FSTYPE" == "btrfs" || "$FSTYPE" == "xfs" ]]; then
-	if [[ `grep -w 'P_VALUE="p1"' "board.txt"` ]]; then
-		# u-boot doesn't support booting directly from this fstype so force a boot partition
-		sed -i 's/P_VALUE="p1"/P_VALUE="p2"/g' board.txt
-	fi
+if [[ "$FSTYPE" =~ ^(btrfs|xfs)$ ]]; then
+	# U-Boot doesn't support booting directly from these fstypes so force a boot partition
+	if [[ `grep -w 'P_VALUE="p1"' "board.txt"` ]]; then sed -i 's/P_VALUE="p1"/P_VALUE="p2"/g' board.txt; fi
 fi
-if [[ -f "custom.txt" ]] && [[ "$ENABLE_EFI" == "true" ]]; then
+if [[ "$ENABLE_BOOTCMD" == "true" ]] && [[ "$ENABLE_PETITBOOT" == "false" ]]; then
+	if [[ `grep -w 'EXTLINUX="true"' "board.txt"` ]]; then sed -i 's/EXTLINUX="true"/EXTLINUX="false"/g' board.txt; fi
+	if [[ `grep -w 'BOOTCMD="false"' "board.txt"` ]]; then sed -i 's/BOOTCMD="false"/BOOTCMD="true"/g' board.txt; fi
+fi
+if [[ "$ENABLE_EFI" == "true" ]]; then
 	sed -i 's/EFI="false"/EFI="true"/g' board.txt
 	if [[ `grep -w 'FAMILY="rockchip"' "board.txt"` ]] && [[ `grep -w 'GPT="false"' "board.txt"` ]]; then
 		sed -i 's/GPT="false"/GPT="true"/g' board.txt
 	fi
-	if [[ `grep -w 'VFAT="false"' "board.txt"` ]]; then
-		sed -i 's/VFAT="false"/VFAT="true"/g' board.txt
-	fi
-	if [[ `grep -w 'P_VALUE="p1"' "board.txt"` ]]; then
-		sed -i 's/P_VALUE="p1"/P_VALUE="p2"/g' board.txt
-	fi
+	if [[ `grep -w 'VFAT="false"' "board.txt"` ]]; then sed -i 's/VFAT="false"/VFAT="true"/g' board.txt; fi
+	if [[ `grep -w 'P_VALUE="p1"' "board.txt"` ]]; then sed -i 's/P_VALUE="p1"/P_VALUE="p2"/g' board.txt; fi
 fi
-if [[ -f "custom.txt" ]] && [[ "$ENABLE_VFAT" == "true" ]]; then
-	if [[ `grep -w 'VFAT="false"' "board.txt"` ]]; then
-		sed -i 's/VFAT="false"/VFAT="true"/g' board.txt
-	fi
-	if [[ `grep -w 'P_VALUE="p1"' "board.txt"` ]]; then
-		sed -i 's/P_VALUE="p1"/P_VALUE="p2"/g' board.txt
-	fi
+if [[ "$ENABLE_VFAT" == "true" ]]; then
+	if [[ `grep -w 'VFAT="false"' "board.txt"` ]]; then sed -i 's/VFAT="false"/VFAT="true"/g' board.txt; fi
+	if [[ `grep -w 'P_VALUE="p1"' "board.txt"` ]]; then sed -i 's/P_VALUE="p1"/P_VALUE="p2"/g' board.txt; fi
 fi
 }
